version: "3"

services:
  app:
    command: >
      bash -c "poetry run python manage.py migrate
      && poetry run python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: library_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sample
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: library_app
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
    postgres:
